language: c
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsofthsm-dev softhsm opensc libp11-dev
  - touch config.rpath && autoreconf -fvi && ./configure

script: make && make check && make dist

